{% set name = "jinxed" %}
{% set version = "2.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a0e9ab57497f53c583d24ae50605790bd46c0ef71b7f777f737476f5109b2c1e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - __{{ target_os }}
    {% if target_os == 'win' %}
    - ansicon
    {% endif %}
    - python >=3.8

test:
  imports:
    - jinxed
    - jinxed.terminfo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/jinxed/
  summary: Jinxed Terminal Library
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mattip
