{% set name = "jinxed" %}
{% set version = "2.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5220778f130e7b9502055dbefaef9cb92ea5c892e72ff2c8e514c8be4d9af9ca

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - __{{ target_os }}
    {% if target_os == 'win' %}
    - ansicon
    {% endif %}
    - python >=3.8

test:
  imports:
    - jinxed
    - jinxed.terminfo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/jinxed/
  summary: Jinxed Terminal Library
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mattip
