{% set name = "jinxed" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8f7801a10799de39e509eb5abc6d131ee169c1ce4fd5d568aa85b5f56ed58068

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - __{{ target_os }}
    {% if target_os == 'win' %}
    - ansicon
    {% endif %}
    - python >=3.8

test:
  imports:
    - jinxed
    - jinxed.terminfo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/jinxed/
  summary: Jinxed Terminal Library
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mattip
